title: Anoosha Tariq
description: Aspiring data analyst with a strong foundation in Chartered Accountancy studies. Proficient in financial accounting, cost accounting, and business analysis, I've also honed my skills in SQL, Python, Jupyter Notebook, and data visualization through specialized courses. Eager to contribute to open-source projects and collaborate on innovative data analysis solutions.
Technical skills: Ms excel Power BI Tableau SQl Python Jupyter Notebook
theme: jekyll-theme-minimal
